config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'site#index'  #only for the home page, nothing else
  get '/about' => 'site#about'
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  # The index action
  # This should list all of our products
  # index.html.erb
  def index
    @products = Product.all
  end

  # This should find a particular product
  # show.html.erb
  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Good Job! You did it.'
      redirect_to products_path
    else
      flash[:alert] = 'Bad job! You failed.'
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
  # define a private method
  # use strong parameters
  def product_params
    params.require(:product).permit(:name)
  end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  # action_name.format.template_engine
  # index.html.erb
  def index
    @products = Product.all
    @cars = Car.all
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_notice_message
    unless flash.empty?
      [:notice, :alert].each do |key|
        return content_tag(:div, flash[key], class: "flash-#{key}") if
        flash[key].present?
      end
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DplStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">
    <header>
      <nav>
        <%= link_to('Home Page', root_path) %>
        <span>&nbsp;|&nbsp;</span>
        <%= link_to('View Products', products_path) %>
        <span>&nbsp|&nbsp;</span>
        <%= link_to('About DPL Store', about_path) %>
      </nav>
    </header>
    <%= show_notice_message %>
    <section id="main-content">
      <%= yield %>
    </section>
    <footer>
      copyright &copy; <%= Time.now.year %>
    </footer>
  </div>

</body>
</html>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= form_for(@product) do |f| %>
  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.submit('Update') %>
  </div>
<% end %>

app/views/products/index.html.erb
<%= link_to('Create a new product', new_product_path) %>

<h1>Showing <%= pluralize(@products.count, 'Product') %></h1>
<ul id="products">
<% @products.each do |product| %>
  <li class="<%= cycle('even', 'odd') %>">
    <%= link_to(product.name, product_path(product.id)) %>
    <%= number_to_currency(product.price) %>
    -- <%= link_to('edit', edit_product_path(product.id)) %>
    -- <%= link_to('delete', product_path(product.id), method: :delete,
    'data-confirm' => 'Are you sure?') %>
    Created <%= time_ago_in_words(product.created_at) %> ago
  </li>
<% end %>
</ul>

app/views/products/new.html.erb
<h1>Make a new product</h1>

<%= form_for(@product) do |f| %>
  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.submit('Save Product') %>
  </div>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= number_to_currency(@product.price) %></h3>
<p>Sku: <%= @product.sku %></p>
<div>
  <%= @product.description %>
</div>

<%= link_to('&laquo; Back to all products'.html_safe, products_path) %>

<!-- <a href="<%# products_path %>">&laquo; Back to all products</a> -->

app/views/site/about.html.erb
<h1>About DPL Store</h1>
<p>
  Pork loin shankle biltong chuck boudin meatball. Kielbasa short loin tongue
  shankle pork loin bacon. Rump pork belly boudin andouille. Ham chuck kielbasa,
  leberkas swine porchetta shoulder chicken filet mignon drumstick.
</p>
<p>
  Shank sirloin venison filet mignon, meatball jowl shoulder capicola meatloaf pastrami.
  Swine leberkas spare ribs strip steak bresaola. Pork belly fatback tail, doner jowl
  ham rump meatball hamburger. Ribeye capicola ball tip bacon porchetta pig pork belly
  filet mignon tongue. Salami corned beef beef ribs short loin jerky andouille. Shoulder
  ribeye kevin swine, tri-tip meatball shankle t-bone fatback pork loin drumstick sirloin
  bresaola pork belly cow. Frankfurter fatback landjaeger jowl chicken biltong.
</p>
<p>
  Porchetta short loin pancetta tenderloin swine, pork leberkas chicken salami beef
  ribs biltong prosciutto beef. Pastrami doner ball tip shank meatloaf. Meatball fatback
  strip steak pork rump. Meatloaf leberkas ham hock fatback, hamburger short loin jowl.
  Brisket drumstick shankle tail, biltong turkey bresaola swine turducken jerky.
</p>

app/views/site/index.html.erb
<h1>Welcome to the DPL Store!</h1>
<%= image_tag('ninja.jpg', size: '100x100') %>

<div class="left-column">
  <h2>Our Products</h2>
  <% @products.each do |product| %>
    <div class="product">
      <%= product.name %>
    </div>
  <% end %>
</div>

<div class="right-column">
  <h2>Our Cars</h2>
  <% @cars.each do |car| %>
    <div class="car">
      <%= car.year %> <%= car.make %> <%= car.model %>
    </div>
  <% end %>
</div>
<br clear="all" />